## Run in production env: (use image: *:latest version only)
## Please read use guide in ./docs/dev-on-docker-env-note.pdf
## please manual create docker-compose.prod.yml on production server to override: ports, volume, image:tag
#     docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
## To see config after merge please run command:
#     docker-compose -f docker-compose.yml -f docker-compose.prod.yml config
version: "3.7"
services:
  bookstore_app:
    environment:
      APP_NAME: BookStore
      APP_ENV: local
      APP_KEY: base64:lMy3JIROh3i7E/fPi9yjHSqbG1qYeLioVSo5Biq4X+Q=
      APP_DEBUG: 1
      APP_URL: http://localhost:8080
      LOG_CHANNEL: stderr
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: bookstore_db
      DB_PORT: 3306
      DB_DATABASE: bookstore
      DB_USERNAME: root
      DB_PASSWORD: huypq29102001
      APPLICATION_ENV: production
